<?php

namespace OC\PlatformBundle\Entity;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository {

    public function getApplicationsWithAdvert($limit) {
        $qb = $this
                ->createQueryBuilder('app')
                ->join('app.advert', 'ad')
                ->addSelect('ad')
                ->setMaxResults($limit)
        ;
        return $qb
                        ->getQuery()
                        ->getResult()
        ;
    }

    public function isFlood($ip, $secondes) {
        $qb = $this
                ->createQueryBuilder('app')
                ->select('COUNT(app)')
                ->where('app.ip = :ip')
                ->setParameter('ip', $ip)
                ->andWhere('app.date >= :date')
                ->setParameter('date', new \Datetime('-' . $secondes . 'seconds'));

        return (bool) $qb->getQuery()->getSingleScalarResult();
    }

}
